-- ==========================================
-- 1. PROFILES
-- Extends the default Supabase 'auth.users' table
-- to store public user information.
-- ==========================================
create table public.profiles (
  -- [PK] Primary Key. Links 1:1 with Supabase Auth User ID.
  id uuid not null references auth.users(id) on delete cascade primary key,

  -- Display name for the leaderboard (e.g., "RhythmMaster99").
  username text unique,

  -- URL to the user's avatar image (can be null if not set).
  avatar_url text,
  
  -- Timestamp for when the profile was last updated.
  updated_at timestamptz default now()
);

-- ==========================================
-- 2. TASKS
-- Represents a "Bi-weekly Challenge" period.
-- Example: "Feb 2026 - 1st Period"
-- ==========================================
create table public.tasks (
  -- [PK] Auto-incrementing ID for the task.
  id bigint generated by default as identity primary key,

  -- The display title of the task (e.g., "Week 4: Stamina Training").
  title text not null,

  -- The exact moment the task opens for submissions.
  start_date timestamptz not null,

  -- The deadline for submissions.
  end_date timestamptz not null,

  -- Soft delete flag. If false, this task is hidden/archived.
  is_active boolean default true,

  -- Creation timestamp for audit purposes.
  created_at timestamptz default now()
);

-- ==========================================
-- 3. JOBS
-- Represents a specific song/chart within a Task.
-- Example: "Canon D - S23"
-- ==========================================
create table public.jobs (
  -- [PK] Auto-incrementing ID for the job.
  id bigint generated by default as identity primary key,

  -- [FK] Links this job to a specific parent Task.
  task_id bigint references public.tasks(id) on delete cascade not null,

  -- The name of the song (e.g., "Conflict", "Mural").
  song_name text not null,

  -- The play style: 'S' for Single, 'D' for Double.
  level_type text not null check (level_type in ('S', 'D')),

  -- The difficulty number (e.g., 23).
  level_number int not null check (level_number between 1 and 28),

  -- Optional: Ordering of songs within the task list (1, 2, 3...).
  sort_order int default 0
);

-- ==========================================
-- 4. SUBMISSIONS
-- The actual "Homework" evidence uploaded by users.
-- ==========================================
create table public.submissions (
  -- [PK] Auto-incrementing ID for the submission.
  id bigint generated by default as identity primary key,

  -- [FK] Which specific job (song) is this for?
  job_id bigint references public.jobs(id) on delete cascade not null,

  -- [FK] Which user submitted this?
  user_id uuid references public.profiles(id) on delete cascade not null,

  -- The public URL of the screenshot stored in Supabase Storage.
  image_url text not null,

  -- Optional comment from the user (e.g., "This took me 5 tries!").
  comment text,

  -- Verification status: 'pending', 'approved', 'rejected'.
  status text default 'pending' check (status in ('pending', 'approved', 'rejected')),

  -- Timestamp when the submission was uploaded.
  created_at timestamptz default now(),

  -- [Constraint] Ensures a user can only submit ONCE per job.
  -- Remove this constraint if you want to allow re-submissions.
  unique(job_id, user_id)
);